
class Universe:
    """ Class where the data generated by the constructors of FreeAlgebra and PBWAlgebra is stored to be accessed by
    all the internal classes."""

    universe = None
    generators = None
    base_field = None
    q_matrix = None
    relations = None

    @classmethod
    def set_universe(self,algebra) -> None:
        Universe.universe = algebra
        Universe.generators = algebra.generators
        Universe.base_field = algebra.base_field
        Universe.q_matrix = algebra.q_matrix

    @classmethod
    def set_pbw_universe(self,pbw_algebra) -> None:
        Universe.pbw_universe = pbw_algebra
        Universe.relations = pbw_algebra.relations